#!/bin/bash
source vars_setup.sh

rclone copy -P --config ${CONFIG_FILE} ${RCLONE_CONFIG}:${DOWNSAMPLE_SUBPATH}/${HOME_REL_DIR} \
    ${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${HOME_REL_DIR}
rclone copy -P --config ${CONFIG_FILE} ${RCLONE_CONFIG}:${DOWNSAMPLE_SUBPATH}/${TRIAL_REL_DIR} \
    ${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${TRIAL_REL_DIR}
rclone copy -P --config ${CONFIG_FILE} ${RCLONE_CONFIG}:${DOWNSAMPLE_SUBPATH}/${TEST_REL_DIR} \
    ${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${TEST_REL_DIR}
rclone copy -P --config ${CONFIG_FILE} ${RCLONE_CONFIG}:${DOWNSAMPLE_SUBPATH}/${CAIMAN_REL_DIR} \
    ${CONFIG_FILE} ${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${CAIMAN_REL_DIR}

