#!/bin/bash

rclone copy -P --config ${CONFIG_FILE} \
	"${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${HOME_REL_DIR}" \
    "${RCLONE_CONFIG}:${UPLOAD_PATH}/${HOME_REL_DIR}"
rclone copy -P --config ${CONFIG_FILE} \
	"${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${TRIAL_REL_DIR}" \
    "${RCLONE_CONFIG}:${UPLOAD_PATH}/${TRIAL_REL_DIR}"
rclone copy -P --config ${CONFIG_FILE} \
	"${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${BEFORETEST_REL_DIR}" \
    "${RCLONE_CONFIG}:${UPLOAD_PATH}/${BEFORETEST_REL_DIR}"
rclone copy -P --config ${CONFIG_FILE} \
	"${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${AFTERTEST_REL_DIR}" \
    "${RCLONE_CONFIG}:${UPLOAD_PATH}/${AFTERTEST_REL_DIR}"
rclone copy -P --config ${CONFIG_FILE} \
	"${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${CAIMAN_REL_DIR}" \
    "${RCLONE_CONFIG}:${UPLOAD_PATH}/${CAIMAN_REL_DIR}"

