#!/bin/bash
set -x
rclone copy --config ${CONFIG_FILE} "${RCLONE_CONFIG}:${SRC_ROOTDIR}/${EXP_MONTH}/rois.csv" \
   "${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${EXP_MONTH}"
rclone copy --config ${CONFIG_FILE} "${RCLONE_CONFIG}:${DOWNSAMPLE_SUBPATH}/${EXP_MONTH}/cnmfe_params.csv" \
    "${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${EXP_MONTH}"
rclone copy -P --config ${CONFIG_FILE} "${RCLONE_CONFIG}:${SRC_ROOTDIR}/${HOME_REL_DIR}" \
    "${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${HOME_REL_DIR}"
rclone copy -P --config ${CONFIG_FILE} "${RCLONE_CONFIG}:${SRC_ROOTDIR}/${TRIAL_REL_DIR}" \
    "${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${TRIAL_REL_DIR}"
rclone copy -P --config ${CONFIG_FILE} "${RCLONE_CONFIG}:${SRC_ROOTDIR}/${AFTERTEST_REL_DIR}" \
    "${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${AFTERTEST_REL_DIR}"
rclone copy -P --config ${CONFIG_FILE} "${RCLONE_CONFIG}:${SRC_ROOTDIR}/${BEFORETEST_REL_DIR}" \
    "${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${BEFORETEST_REL_DIR}"
