#!/bin/bash
#rclone copy --config ${CONFIG_FILE} ${RCLONE_CONFIG}:${DOWNSAMPLE_SUBPATH}/${EXP_MONTH}/cnmfe_params.csv \
#    ${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${EXP_MONTH}
rclone copy -P --config ${CONFIG_FILE} ${RCLONE_CONFIG}:${DOWNSAMPLE_SUBPATH}/${CAIMAN_REL_DIR} \
    ${LOCAL_ROOTDIR}/${DOWNSAMPLE_SUBPATH}/${CAIMAN_REL_DIR}
